// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://veyzteknzcpflawyekau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZleXp0ZWtuemNwZmxhd3lla2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzc4NzksImV4cCI6MjA2NTkxMzg3OX0.-pmBmgzCtzduKubo6VMbpnjjtr0LRNx9V3WTjn_RMFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);